### ISSUE TITLE
Sequence Identifier labels are truncated

### ISSUE THREAD

**Issue by dmgood11** [JGI-Eukaryotes/msa#1]
Label div's are set to 120 px. Need to make them wide enough for largest identifier in set.
![screen shot 2018-01-08 at 4 42 27 pm](https://user-images.githubusercontent.com/6620403/34699572-f1b8b5d4-f492-11e7-833d-1131f751935a.png)

**Comment by dmgood11** [comment]
attribute "labelNameLength" in g/zoomer.js is set to 100.

**Comment by dmgood11** [comment]
Here's an example family where the MSA shows label truncation:  https://njp-spin.jgi.doe.gov/report/family/5270/124074730

**Comment by pacdavidson** [comment]
Superseded by adoption of GMOD's react-msaview module.
