### ISSUE TITLE
Misalignment of additional Vis. elements with MSA columns in Firefox and Chrome

### ISSUE THREAD

**Issue by dmgood11** [JGI-Eukaryotes/msa#2]
Steps to reproduce:

1. load https://phytozome-dev.jgi.doe.gov/api/db/html/exampleMSA.html
2. Go to "Vis. elements ->Show Sequence logo"
3. Go to "Vis. elements ->Show Conservation weights"

In Chrome 63.0.3239.84 and Firefox 57.0.1, those two Vis. elements are left-shifted relatively to the corresponding MSA residue column.  Fine in Safari (see attached Safari image).  

Looks like Chrome and Firefox are not correctly accounting for width of vert sequence scrollbar. as everythign seems to align better in Chrome and Firefox once I delete enough to sequences to make scrollbar disappear. 

![screen shot 2018-01-08 at 4 48 32 pm](https://user-images.githubusercontent.com/6620403/34699742-df2514de-f493-11e7-87c2-b260ca4e773e.png)

**Comment by pacdavidson** [comment]
Superseded by adoption of GMOD's react-msaview component. See https://github.com/JGI-Eukaryotes/zome-react-msaview.
