### ISSUE TITLE
Export does not respect MSA edits, specifically removal of sequences

### ISSUE THREAD

**Issue by dmgood11** [JGI-Eukaryotes/msa#4]
If I "hide" a bunch of sequences and then export the MSA (try exporting as FASTA format), all the sequences are present.

Perhaps that's why the Filter menu says "Hide" instead of "Delete" sequence.  

Still, would be nice if "hidden" sequences, columns could be excluded from exports.

**Comment by pacdavidson** [comment]
Rolled into zome-react-msaview requirements in https://github.com/JGI-Eukaryotes/zome-react-msaview/issues/2.
