### ISSUE TITLE
Residues block and identifiers block get decoupled w.r.t. vert scrolling after sequence hiding

### ISSUE THREAD

**Issue by dmgood11** [JGI-Eukaryotes/msa#5]
Hiding sequences decouples sequence displays from identifier displays.

1.  Go to https://phytozome-dev.jgi.doe.gov/api/db/html/exampleMSA.html
2.  Scroll down and Shift-select 12 of the bottom sequences.  Select "Hide Sequence by selection"
3.  note remaining image, and decoupling of vert scrolling of residues block from identifiers block

Most  dramatic on Safari:

![before vert scroll](https://user-images.githubusercontent.com/6620403/34700901-3da06c60-f49a-11e7-9932-cee37c9dc904.png)
3

**Comment by pacdavidson** [comment]
Superseded by use of GMOD's react-msaview: see https://github.com/JGI-Eukaryotes/zome-react-msaview.
